---
title: "group_document"
format: html
editor: visual
---

## Carlos

```{r}

library(tidyverse)
print("Try a cool plot")

x <- c(1, 2, 3, 4, 5)
y <- c(2, 4, 6, 8, 10)

plot(x, y, 
     main = "Scatter Plot Example",
     xlab = "X-axis",
     ylab = "Y-axis",
     pch = 19,       
     col = "blue"
)

```

## Laura

Print something

```{r}
print("Hola")
```

### New feature

jjfalkhglakdhglasghladksglakdnjhkj

## Monika

```{r}
print('Henlo world')
```

### New feature

```{r}
print('How was your day?')
```

## Amanda

Amanda was here :)

```{r}
data <- data.frame()

```

### New analysis

Amanda was also here

```{r}
print("La cucaracha, la cucarachaa")
```

## Ana

s222761

```{r}
print("Viva Soria")
```

s222761

```{r}
library(ggplot2)

# Generate the data
my_data <- data.frame(x = rnorm(n = 5000,
                               mean = 27,
                               sd = 10))

# Create the histogram
my_data |>
  ggplot(aes(x = x)) +
  geom_histogram(binwidth = 1,
                 color = "black",
                 fill = "cornflowerblue") +
  labs(title = "My Histogram",
       x = "Values",
       y = "Frequency") +
  theme_minimal()
```
